version: '2'

services:
  db:
    build: bd
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  php:
    build:
      context: php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${SYMFONY_APP}:/var/www/symfony
      - ./logs/symonfy:/var/www/symonfy/var/logs
  nginx:
    build:
      context: nginx
    ports:
      - 85:80
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx