version: '2'

services:
  db:
    image: mysql
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PAWWSORD: ${MYSQL_PASSWORD}
  php:
    build:
      context: php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
